In [33]:
import pandas as pd 
import numpy as np

- list 
- dict 
- variable 
- for 
- while 
- if 
- try 
- except

'13salut00'

In [102]:
matrix = np.random.randn(10,10)
df = pd.DataFrame(matrix)

In [103]:
df

,0,1,2,3,4,5,6,7,8,9
0,1.696279,-0.004546,0.632222,-0.153239,1.317298,-0.596081,0.310942,1.125192,0.174431,2.360693
1,0.830550,-1.049532,-1.505810,0.558956,-1.172090,0.285349,0.302689,-1.354945,0.600736,-1.386669
2,-1.683089,-0.031218,-0.113686,0.849841,0.450700,-0.400757,-1.754507,-0.173551,-0.123055,-0.557331
3,-0.528733,0.265340,0.969120,0.098037,0.588198,1.264295,1.989115,0.244346,0.876301,-1.921806
4,0.094626,-0.594615,0.483039,0.051654,-0.969270,0.696874,2.288630,-1.576487,-0.974601,1.300804
5,0.470587,-0.363228,0.248537,-1.732770,0.078311,0.711379,0.105799,0.728082,0.337376,0.414349
6,-0.228683,0.177368,-0.456230,0.988550,1.434036,0.833574,1.965964,1.429333,1.857174,-2.172060
7,0.041050,-0.563726,2.817171,-0.860005,-0.239174,1.219977,-0.138199,-0.161666,-0.405001,-1.159737
8,-1.055232,1.130753,-0.141109,0.773555,-0.424881,-0.421448,-0.347361,-1.076173,-0.377966,0.660386
9,1.434010,0.867662,-1.827507,0.905861,-0.798364,-0.081411,-1.055751,-0.181517,-1.987737,-0.375400

In [104]:
df["nom"] = ["a"*n for n in range(1,11)]

In [105]:
df

,0,1,2,3,4,5,6,7,8,9,nom
0,1.696279,-0.004546,0.632222,-0.153239,1.317298,-0.596081,0.310942,1.125192,0.174431,2.360693,a
1,0.830550,-1.049532,-1.505810,0.558956,-1.172090,0.285349,0.302689,-1.354945,0.600736,-1.386669,aa
2,-1.683089,-0.031218,-0.113686,0.849841,0.450700,-0.400757,-1.754507,-0.173551,-0.123055,-0.557331,aaa
3,-0.528733,0.265340,0.969120,0.098037,0.588198,1.264295,1.989115,0.244346,0.876301,-1.921806,aaaa
4,0.094626,-0.594615,0.483039,0.051654,-0.969270,0.696874,2.288630,-1.576487,-0.974601,1.300804,aaaaa
5,0.470587,-0.363228,0.248537,-1.732770,0.078311,0.711379,0.105799,0.728082,0.337376,0.414349,aaaaaa
6,-0.228683,0.177368,-0.456230,0.988550,1.434036,0.833574,1.965964,1.429333,1.857174,-2.172060,aaaaaaa
7,0.041050,-0.563726,2.817171,-0.860005,-0.239174,1.219977,-0.138199,-0.161666,-0.405001,-1.159737,aaaaaaaa
8,-1.055232,1.130753,-0.141109,0.773555,-0.424881,-0.421448,-0.347361,-1.076173,-0.377966,0.660386,aaaaaaaaa
9,1.434010,0.867662,-1.827507,0.905861,-0.798364,-0.081411,-1.055751,-0.181517,-1.987737,-0.375400,aaaaaaaaaa